<template>
  <div class="student-schedule">
    <div class="card">
      <div class="card-header">
        <span class="card-title">Thời khóa biểu</span>
        <el-select v-model="selectedSemester" placeholder="Chọn học kỳ" @change="loadSchedule">
          <el-option v-for="sem in semesters" :key="sem.id" :label="sem.name" :value="sem.id" />
        </el-select>
      </div>

      <div class="schedule-grid">
        <div class="grid-header">
          <div class="grid-cell time-col">Tiết / Thứ</div>
          <div v-for="day in 6" :key="day" class="grid-cell day-col">Thứ {{ day + 1 }}</div>
          <div class="grid-cell day-col">Chủ nhật</div>
        </div>
        
        <div v-for="period in 10" :key="period" class="grid-row">
          <div class="grid-cell time-col">Tiết {{ period }}</div>
          
          <div v-for="day in 6" :key="day" class="grid-cell day-cell">
            <template v-if="getScheduleItem(day + 1, period)">
              <div 
                v-if="shouldShowItem(day + 1, period)"
                class="class-item"
                :style="{ height: getItemHeight(day + 1, period) }"
              >
                <div class="class-name">{{ getScheduleItem(day + 1, period).subjectName }}</div>
                <div class="class-room">{{ getScheduleItem(day + 1, period).scheduleInfo }}</div>
              </div>
            </template>
          </div>
          
          <div class="grid-cell day-cell">
             <!-- Sunday (day 8 in data or 1? assuming 2-7 is Mon-Sat, 8 Sun) -->
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useAuthStore } from '../../stores/auth'
import api from '../../api'

const authStore = useAuthStore()
const semesters = ref([])
const selectedSemester = ref('')
const scheduleData = ref([])

// Mock schedule data mostly because BE endpoint needs correct semesterId which we first need to fetch
// But real implementation will use `loadSchedule`

const loadSemesters = async () => {
    try {
        const response = await api.get('/api/admin/semesters', { params: { size: 100 } })
        if (response.data.success) {
            semesters.value = response.data.data.items || []
            if (semesters.value.length > 0) {
                // Select the latest one or active one ideally
                selectedSemester.value = semesters.value[0].id
                loadSchedule()
            }
        }
    } catch (error) {
        console.error("Failed to load semesters", error)
    }
}

const loadSchedule = async () => {
    if (!selectedSemester.value) return
    try {
        const response = await api.get(`/api/student/${authStore.user.id}/schedule`, {
            params: { semesterId: selectedSemester.value }
        })
        if (response.data.success) {
            scheduleData.value = response.data.data.scheduleItems || []
        }
    } catch (error) {
        console.error("Failed to load schedule", error)
    }
}

// Helpers for the grid
// Parsing "Thứ 2 (1-3)" is tricky if the BE returns unstructured string. 
// However, the `scheduleInfo` field is just a string. 
// Ideally BE should return structured `dayOfWeek`, `startPeriod`, `endPeriod`.
// Checking the OpenAPI `ScheduleItem` in response `MyScheduleResponse`:
// properties: `scheduleItems`: array of `ScheduleItem`
// `ScheduleItem` has: `scheduleInfo` (string), `courseCode`, etc.
// It seems the current BE only returns a summary string "T2 (1-3)". 
// We need to parse this string to render the grid! OR the BE provides structured data.
// Looking at `CourseSchedule` entity, it has day/start/end.
// But `MyScheduleResponse` projection might not have it broken down.
// Let's check `MyScheduleResponse` content in recent `ApplicationInitConfig.java`... 
// Wait, `MyScheduleResponse` DTO was in the list of files I removed comments from.
// It matches the OpenAPI. 
// So I will implement a parser for the standard format "Thứ X (Tiết A-B)" generated by current data seeder.

const parseSchedule = (scheduleInfo) => {
    // Format: "Thứ 2 (Tiết 1-3)" or "T2 (1-3), T4 (1-3)"
    // Simple regex for "Thứ (\d) \(Tiết (\d+)-(\d+)\)"
    const regex = /Thứ (\d) \(Tiết (\d+)-(\d+)\)/g;
    const matches = []
    let match;
    while ((match = regex.exec(scheduleInfo)) !== null) {
        matches.push({
            day: parseInt(match[1]),
            start: parseInt(match[2]),
            end: parseInt(match[3])
        })
    }
    return matches;
}

// Transform flat schedule list into a map for easy lookup
const scheduleMap = ref(new Map())

const updateScheduleMap = () => {
    const map = new Map()
    scheduleData.value.forEach(item => {
        const parts = parseSchedule(item.scheduleInfo)
        parts.forEach(part => {
             const key = `${part.day}-${part.start}`
             map.set(key, { ...item, ...part })
             // Mark subsequent periods as occupied by same class
             for (let i = part.start + 1; i <= part.end; i++) {
                 map.set(`${part.day}-${i}`, { ...item, ...part, isExtension: true, startPeriod: part.start })
             }
        })
    })
    scheduleMap.value = map
}

import { watch } from 'vue'
watch(scheduleData, updateScheduleMap)

const getScheduleItem = (day, period) => {
    return scheduleMap.value.get(`${day}-${period}`)
}

const shouldShowItem = (day, period) => {
    const item = getScheduleItem(day, period)
    return item && !item.isExtension
}

const getItemHeight = (day, period) => {
    const item = getScheduleItem(day, period)
    if (!item) return '0px'
    const duration = item.end - item.start + 1
    // row height 50px + gap ? Let's use simpler CSS row spanning if grid.
    // But since I used flex/divs:
    return `${duration * 50}px` 
}

onMounted(() => {
    loadSemesters()
})
</script>

<style scoped>
.student-schedule {
    /* ... */
}
.schedule-grid {
    border: 1px solid #dcdfe6;
    display: flex;
    flex-direction: column;
}
.grid-header, .grid-row {
    display: flex;
}
.grid-header {
    background-color: #f5f7fa;
    font-weight: bold;
    border-bottom: 1px solid #ebeef5;
}
.grid-cell {
    flex: 1;
    border-right: 1px solid #ebeef5;
    min-height: 50px;
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
}
.grid-row {
    border-bottom: 1px solid #ebeef5;
}
.time-col {
    flex: 0 0 100px;
    background-color: #fafafa;
}
.class-item {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    background-color: #ecf5ff;
    border-left: 4px solid #409eff;
    padding: 4px;
    z-index: 1;
    overflow: hidden;
    font-size: 12px;
    box-sizing: border-box;
}
.class-name {
    font-weight: bold;
    color: #303133;
}
.class-room {
    color: #909399;
}
</style>
